### PR TITLE
Backend Logs

### PR DESCRIPTION
**Pull request by aidanouckama**
After some infiltration within our database through our (NAKED) API, decided to add some logs to make sure we can keep an eye on individuals trying to playfully pentest our creation.

**Backend Logs**
- `server/controllers/authController.js` - Removed the old logs of just printing out the user information, and added information on who logged in, along with the user's information.

- `server/controllers/*` - Added logs to PUT, PATCH, and DELETE requests, logging what information has been updated and/or written to.
- `server/models/userModel.js` - Added logs to print out when users log in.

LONG LIVE PIPELINES 🚀

### CODE REVIEW

**Review by Lewin-B — APPROVED** [review]
lgtm

**Comment by aidanouckama** [comment]
> Your [Render](https://render.com) PR Server URL is https://pipelines-pr-137.onrender.com.
> 
> Follow its progress at https://dashboard.render.com/web/srv-co5mh463e1ms73ed0qf0.

Backend LGTM.

**Comment by aidanouckama** [comment]
Wait what am I doing this was merged.

**Comment by aidanouckama** [comment]
The voices are getting louder.

**Pull request merged**
