### PR TITLE
Admin Page

### PR DESCRIPTION
**Pull request by aidanouckama**
Added an admin page to make it easier for us to manipulate company data.

### CODE REVIEW

**Review by Lewin-B — CHANGES_REQUESTED** [review]
Rebase main onto this branch and resolve the conflicts

**Review by Nyumat — APPROVED** [review]
LGTM, after the suggested fixes by Lewin, should be good to go

**Comment by HarryZ10** [comment]
#125

**Comment by aidanouckama** [comment]
> #125

Hey Harry! We actually don't use those tokens anymore, since we need the user to have a token even if they haven't logged in. We're probably going to remove those in another PR. 

The tokens we use now are in [https://github.com/pipelines-lol/pipelines/tree/secure-api](/pipelines-lol/pipelines/tree/secure-api), if you want to take a look into those!

**Review by arfpog — APPROVED** [review]

**Comment by HarryZ10** [comment]
> > #125
> 
> Hey Harry! We actually don't use those tokens anymore, since we need the user to have a token even if they haven't logged in. We're probably going to remove those in another PR.
> 
> The tokens we use now are in [https://github.com/pipelines-lol/pipelines/tree/secure-api](/pipelines-lol/pipelines/tree/secure-api), if you want to take a look into those!

Yes that was just an example of how you can encode `isAdmin` instead of assigning the mode in cookies directly. In short, it might be worth using tokens for admin auth flow too.

**Pull request closed without merging**
