### PR TITLE
Initial Documentation Boilerplate and SEO Buffs

### PR DESCRIPTION
**Pull request by Nyumat**
Now that we're officially in the ALPHA phase of our release, it's a good time to start adding search engine optimization (SEO) and public-facing docs for our open-source pursuits; with items such as a README, contributor guidelines, and code of conduct.

What I did was go-ahead and add these items.

**Docs Items:**
- `README.md` - Summary of the project, guidelines, and contact information.
- `CONTRIBUTING.md` - Guidelines for prospective maintainers & contributors.
- `CODE_OF_CONDUCT.md` - Helps us maintain a safe and welcoming space for the contributors and the community.

**SEO Items:**
- Open Graph Twitter, Facebook, and Google meta tags - 
- Static preview png image of the pipelines website hero section

Cheers 🚀

### CODE REVIEW

**Review by arfpog — APPROVED** [review]
fire SEO bro

**Review by aidanouckama — APPROVED** [review]
this is so good oh my orz

**Review by Lewin-B — APPROVED** [review]
lgtm

**Comment by Nyumat** [comment]
Was missing a closing `"` char in an html element, my bad y'all 😅

**Pull request merged**
