### PR TITLE
style[js]: adjust font for Testimony section

### PR DESCRIPTION
**Pull request by vanshb03**
Changed the testimony name section from light to normal @Nyumat

Light was just super dimmed out due to the weight and color const

### CODE REVIEW

**Review by Nyumat — APPROVED** [review]
LGTM! Thanks for adjusting this. 

minor nit for next time  --> squash these two commits into one

**Comment by vanshb03** [comment]
> LGTM! Thanks for adjusting this.
> 
> minor nit for next time --> squash these two commits into one

I made a mistake the first time - did semi-bold instead of normal :(

**Comment by Nyumat** [comment]
haha no worries 🤙🏿

**Review by aidanouckama — APPROVED** [review]
My goat 🐐

**Pull request merged**
