### PR TITLE
Added present date feature and date input validation

### PR DESCRIPTION
**Pull request by Lewin-B**
Added the present date feature for fulltime roles and fixed the date input validation on the experience form

### CODE REVIEW

**Comment by Ouckah** [comment]
Not sure what is causing the error, but when I input a "Present" option in one of the fields, and try to submit, it spits an "Invalid Date" error. Here's the case that created it:

image

**Review by aidanouckama — CHANGES_REQUESTED** [review]
Not sure what is causing the error, but when I input a "Present" option in one of the fields, and try to submit, it spits an "Invalid Date" error. Here's the case that created it:

image

**Comment by Lewin-B** [comment]
> Not sure what is causing the error, but when I input a "Present" option in one of the fields, and try to submit, it spits an "Invalid Date" error. Here's the case that created it:
> 
> image

This is becuase septemeber 2024 is a date that is after the current date so it makes no sense to be working from septemeber 2024 to the present

**Comment by aidanouckama** [comment]
I'm braindead, approved.

**Review by aidanouckama — APPROVED** [review]

**Pull request merged**
